---
title: "Econometria I"
author: "Lista de Exercícios 3"
affiliation: PIMES/UFPE
abstract:
thanks:
keywords:
date: "PIMES/UFPE"
output:
  pdf_document:
    highlight: default
    #citation_package:
    keep_tex: false
    #fig_caption: true
    latex_engine: pdflatex
fontsize: 11pt
geometry: margin=1in
#bibliography:
#biblio-style:
header-includes:
- \usepackage{indentfirst}
- \usepackage{graphicx}
- \usepackage{geometry}
- \usepackage{subfigure}
- \usepackage{amsmath}
- \usepackage{listings}
- \usepackage{tikz}
- \usetikzlibrary{matrix}
---

\vspace{0.25in}




# Problemas conceituais


1. Uma regressão múltipla de $y$ em uma constante, $x_1$ e $x_2$ produz os seguintes resultados: $\hat{y} = 4 + 0,4x_1 + 0,9x_2$, $R^2 = 8/60$, $\mathbf{e'e} = 520$, $n = 29$, 
$$\mathbf{X'X}=
\begin{bmatrix} 
  29 &   0 & 0  \\
  0 &   50 & 10  \\
  0 &   10 &  80 \\
  \end{bmatrix}$$
Teste a hipótese de que os coeficientes de inclinação somam 1.

2. Prove o resultado de que o estimador de mínimos quadrados restrito nunca tem uma matriz de covariância maior do que o estimador de mínimos quadrados irrestrito.

3. Prove o resultado de que o $R^2$ associado a um estimador de mínimos quadrados restrito nunca é maior que aquele associado ao estimador de mínimos quadrados irrestrito. Conclua que a imposição de restrições nunca melhora o ajuste da regressão.

4. Suponha que temos $n$ observações $iid$ $(y_i, \mathbf{x}_{1i}, \mathbf{x}_{2i})$ e considere dois modelos de regressão alternativos $$y_i = \mathbf{x}_{1i}'\pmb{\beta}_1 + \varepsilon_{1i}$$ $$y_i = \mathbf{x}_{2i}'\pmb{\beta}_2 + \varepsilon_{2i}$$ onde $E(\mathbf{x}_{1i}\varepsilon_{1i})=0$ e $E(\mathbf{x}_{1i}\varepsilon_{1i})=0$. Ademais, $\mathbf{x}_{1i}$ e $\mathbf{x}_{2i}$ têm pelo menos alguns regressores diferentes. (Por exemplo, (1) é uma regressão salarial em variáveis geográficas e (2) é uma regressão salarial em variáveis individuais.) Queremos saber se o modelo (1) ou o modelo (2) representa melhor os dados. Defina $\sigma_1^2=E(\varepsilon_{1i}^2)$ e $\sigma_2^2=E(\varepsilon_{2i}^2)$. Suponha que decidimos pelo modelo com a menor variância (por exemplo, modelo (1) é melhor se $\sigma_1^2<\sigma_2^2$.) Você decide testar a hipótese $H_0\text{: }\sigma_1^2=\sigma_2^2$ contra a alternativa $H_1\text{: }\sigma_1^2\neq\sigma_2^2$.

    a. Construa um estimador $\hat{\theta}$ de $\theta= \sigma_1^2-\sigma_2^2$
    b. Encontre a distribuiçāo assintótica de $\sqrt{n}(\hat{\theta}-\theta)$ quando $n \rightarrow \infty$.
    c. Proponha um teste assintótico de $H_0$ contra $H_1$ de tamanho $\alpha$.

5. Quais são os pressupostos chaves do estimador de variáveis instrumentais?

6. Prove que o estimador de 2SLS é **viesado** e **consistente**.

7. Derive a formula do estimador de variável instrumental quando o numero de instrumentos é igual ao número de variáveis endógenas. 

8. Considere o modelo $$\begin{split} y_{1i} = & \beta y_{2i} + \varepsilon_{1i} \\
y_{2i} = & \alpha x_{i} + \varepsilon_{2i}\end{split}$$ onde $$\mathbf{\varepsilon}_i=\begin{bmatrix} \varepsilon_{1i} \\
\varepsilon_{2i}\end{bmatrix}\sim iid \text{ } N \left(\begin{bmatrix} 0 \\
0 \end{bmatrix},\begin{bmatrix} \sigma_{11} & \sigma_{12} \\
\sigma_{12} & \sigma_{22} \end{bmatrix}\right),$$ $y_{1i}$ e $y_{2i}$ são as variáveis dependentes (univariadas) e $x_i$ é uma variável aleatória exógena (univariada). A amostra contém $n$ observações de $(y_{1i}, y_{2i}, x_i)$.
    a. Derive o estimador de OLS de $\beta$. Analise a consistência desse estimador.
    b. Se não for consistente, você pode impor algumas restrições nos parâmetros do modelo para recuperar consistência? Interprete e discuta seu resultado.
    c. Derive o estimador de OLS de $\alpha$. Analise a consistência desse estimador.
    d. Se não for consistente, você pode impor algumas restrições nos parâmetros do modelo para recuperar consistência? Interprete e discuta seu resultado.
    e. Derive o estimador IV de $\beta$ usando $x$ como instrumento e estude sua consistência. Qual estimador de $\beta$ deve ser usado? Interprete e discuta sua resultado.
    
