---
title: "Econometria I"
author: "Lista de Exercícios 4"
affiliation: PIMES/UFPE
abstract:
thanks:
keywords:
date: "PIMES/UFPE"
output:
  pdf_document:
    highlight: default
    #citation_package:
    keep_tex: false
    #fig_caption: true
    latex_engine: pdflatex
fontsize: 11pt
geometry: margin=1in
#bibliography:
#biblio-style:
header-includes:
- \usepackage{indentfirst}
- \usepackage{graphicx}
- \usepackage{geometry}
- \usepackage{subfigure}
- \usepackage{amsmath}
- \usepackage{listings}
- \usepackage{tikz}
- \usetikzlibrary{matrix}
---

\vspace{0.25in}




# Problemas conceituais


1. Calcule algebricamente a matriz de covariância de OLS sob heterocedasticidade e/ou autocorrelação.

2. Descreva o estimador da matriz de covariancia robusta de White. Ele corrige a heterocedasticidade?

3. Calcule matricialmente o estimador de Mínimos quadrados generalizados (GLS) e mostre que ele é consistente.

4. Qual a principal consequência de ignorar a estrutura "clusterizada" dos dados numa regressão por OLS?

5. Imagine que você tem dados ao nível de municípios brasileiros para o ano 2000, do PIB e escolaridade média, onde a última é a variável explanatória. Se você usar erro padrão por cluster de Estado, você estaria controlando por qual possível problema?

6. Considere o modelo de regressão linear múltipla: $$y_i = \beta_0 + \beta_1 x_{i1} + \beta_2 x_{i2} + \epsilon_i$$ A matriz de covariância $\Sigma$ é dada por: $$\Sigma = \begin{bmatrix} \sigma_1^2 & 0 & \cdots & 0 \\ 0 & \sigma_2^2 & \cdots & 0 \\ \vdots & \vdots & \ddots & \vdots \\ 0 & 0 & \cdots & \sigma_n^2 \end{bmatrix}$$ onde a variância do erro para a observação $i$, $\sigma_i^2$, é dada por $\lambda_i\sigma^2$, onde $\lambda_i$ é uma constante conhecida.
    a. Discuta as implicações de se estimar o modelo acima pelo método OLS. Lembre-se de explicitar quaisquer pressupostos usados em sua resposta.
    b. Derive o estimador de mínimos quadrados generalizados (GLS) para o modelo acima.
    c. Compare os estimadores de OLS ($\mathbf{b}_{OLS}$) e GLS ($\mathbf{b}_{GLS}$) em termos de eficiência e consistência.
    d. Derive uma forma de construir a matriz de covariância de $\mathbf{b}_{OLS}$ levando em conta a estrutura heteroscedástica de $\varepsilon$.
    e. Descreva um teste formal para a presença de heteroscedasticidade no modelo de regressão. Esboce os passos para conduzir o teste e interprete os resultados.
    
7. Responda as seguintes questões sobre dados em painel:

    a. Mostre que na presencia de heterogeneidade não observada correlacionada com a variável principal $X$, o estimador de desvio de media (*within estimator*) é consistente e não-viesado.
     b. Se existe heterogeneidade não observada que não está correlacionada com a variável $X$ de interesse, qual estimador seria mais apropriado: efeito        fixo ou efeito aleatório? Por que?


8. Responda as seguintes questões sobre dados em painel:

    a. Mostre que se existe heterogeneidade não observada, o estimador de OLS é ineficiente.
    b. Mostre que na presencia de heterogeneidade não observada correlacionada com a variável principal $X$, o estimador de desvio de media (*within estimator*)      é consistente e não-viesado.
     c. Se existe heterogeneidade não observada que não está correlacionada com a variável $X$ de interesse, qual estimador seria mais apropriado: efeito        fixo ou efeito aleatório? Por que?
     d. Considere um modelo de efeitos fixos, ou algum modelo que visa eliminar a heterogeneidade não observada dos dados. O que aconteceria se você incluir uma variável que varia entre unidades $i$, mas que não varia ao longo do tempo (exemplo, sexo, raça)?
  

     
# Problemas práticos

Considere o seguinte modelo: $$Renda_{it}=\alpha + \beta Seca_{it} + \phi_i + \delta_t + \varepsilon_{it}$$ onde $Renda$ é a renda agrícola do município $i$ no ano $t$. $Seca$ é uma variável dummy que é igual a 1 se houve seca no ano $t$. O efeito fixo de município é dado por $\phi_i$, enquanto o efeito fixo de tempo é dado por $\delta_t$.

1. Responda as seguintes questões práticas sobre esse modelo:

    a. O que aconteceria se rodassemos este modelo por OLS e ignorar os efeitos fixos de tempo e ano? O estimador seria inconsistente e não-viesado?
    b. Que fatores em $\phi_i$ poderiam estar correlacionados com $Seca$? Ofereça exemplos.
    c. Que fatores em $\delta_t$ poderiam estar correlacionados com $Seca$? Ofereça exemplos.
    d. O que poderia acontecer se omitissemos o efeito fixo de tempo, mas incluissemos o de ano? O estimador seria inconsistente e não-viesado?
    e. O que poderia acontecer se incluissemos tanto os efeitos fixos de tempo e município no modelo? Estimador seria inconsistente e não-viesado?
    f. Ainda se incluissemos ambos os efeitos fixos, que variável omitida relevante poderia estar dentro do termo de erro $\varepsilon_{it}$? Ofereça um exemplo.
    